# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarios', models.CharField(choices=[('Vazio', 'Indefinido'), ('1M', '07:00 - 08:30'), ('2M', '08:50 - 10:20'), ('3M', '10:30 - 12:00'), ('1T', '13:00 - 14:30'), ('2T', '14:50 - 16:20'), ('3T', '16:30 - 18:00'), ('1N', '18:00 - 19:50'), ('2N', '20:00 - 22:00')], default='Vazio', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=12)),
                ('nome', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horario',
            field=models.ManyToManyField(to='appsispac.Horario'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsispac.Professor'),
        ),
    ]
