# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-13 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsispac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='horarios',
            field=models.CharField(choices=[('Vazio', 'Indefinido'), ('07:00 - 08:30', '1M'), ('08:50 - 10:20', '2M'), ('10:30 - 12:00', '3M'), ('13:00 - 14:30', '1T'), ('14:50 - 16:20', '2T'), ('16:30 - 18:00', '3T'), ('18:00 - 19:50', '1N'), ('20:00 - 22:00', '2N')], default='Vazio', max_length=30),
        ),
    ]
