# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appsispac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=30)),
                ('situacao', models.CharField(choices=[('NR', 'Aula não realizada'), ('AR', 'Aula realizada')], default='NR', max_length=2)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsispac.Disciplina')),
            ],
        ),
    ]
