# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appsispac', '0002_frequencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='professor',
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professor',
            field=models.ManyToManyField(to='appsispac.Professor'),
        ),
    ]
